[[locations]]
file = "pyproject.toml"
type = "pyproject-version"

[[locations]]
file = "python/pyproject.toml"
type = "pyproject-version"

[[locations]]
file = "python/oemmpa/__init__.py"
type = "python-dunder"

[[locations]]
file = "python/oemmpa/__init__.py"
type = "python-version-info"

[[locations]]
file = "CMakeLists.txt"
type = "cmake-project"

[[locations]]
file = "include/oemmpa/oemmpa.h"
type = "c-define"
prefix = "OEMMPA"

[[locations]]
file = "swig/oemmpa.i"
type = "c-define"
prefix = "OEMMPA"

[[locations]]
file = "tests/python/test_oemmpa.py"
type = "custom"
template = 'oemmpa\.__version__ == "{version}"'
label = "test-version-string"

[[locations]]
file = "tests/python/test_oemmpa.py"
type = "custom"
template = 'oemmpa\.__version_info__ == \({info_tuple}\)'
label = "test-version-info"
