#ifndef OEMMPA_TRANSFORM_APPLICATION_H
#define OEMMPA_TRANSFORM_APPLICATION_H

#include <string>
#include <vector>

#include <oechem.h>

#include "oemmpa/MatchedPair.h"

namespace OEMMPA {

/// \brief Product generated by applying a transform.
class TransformProduct {
public:
    TransformProduct() = default;
    explicit TransformProduct(const std::string& smiles);

    /// \brief Canonical product SMILES.
    ///
    /// \returns Canonical product SMILES generated by OpenEye.
    const std::string& GetSmiles() const;

private:
    std::string smiles_;
};

/// \brief Applies chemically explicit molecular transforms.
class TransformApplicator {
public:
    /// \brief Apply a unimolecular transform SMIRKS to a source SMILES.
    ///
    /// \param source_smiles Source molecule SMILES.
    /// \param transform_smirks Chemically explicit unimolecular SMIRKS.
    /// \returns Deduplicated canonical product SMILES records.
    /// \throws InvalidMoleculeError If the source SMILES is invalid.
    /// \throws InvalidQueryError If the transform SMIRKS cannot be parsed.
    static std::vector<TransformProduct> ApplySmirks(
        const std::string& source_smiles,
        const std::string& transform_smirks
    );

    /// \brief Apply a unimolecular transform SMIRKS to an OpenEye molecule.
    ///
    /// \param source_mol Source molecule.
    /// \param transform_smirks Chemically explicit unimolecular SMIRKS.
    /// \returns Deduplicated canonical product SMILES records.
    /// \throws InvalidMoleculeError If the source molecule has no atoms.
    /// \throws InvalidQueryError If the transform SMIRKS cannot be parsed.
    static std::vector<TransformProduct> ApplySmirks(
        const OEChem::OEMolBase& source_mol,
        const std::string& transform_smirks
    );

    /// \brief Convert an observed single-cut variable transform to SMIRKS.
    ///
    /// \param variable_transform_smiles Transform string in
    ///     ``source_variable>>target_variable`` form.
    /// \returns Reaction-ready SMIRKS for the supported single-atom case.
    /// \throws InvalidQueryError If the transform is malformed or unsupported.
    static std::string BuildVariableTransformSmirks(
        const std::string& variable_transform_smiles
    );

    /// \brief Convert observed single-cut variables to SMIRKS.
    ///
    /// \param source_variable_smiles Source variable SMILES.
    /// \param target_variable_smiles Target variable SMILES.
    /// \returns Reaction-ready SMIRKS for the supported single-atom case.
    /// \throws InvalidQueryError If either variable is malformed or unsupported.
    static std::string BuildVariableTransformSmirks(
        const std::string& source_variable_smiles,
        const std::string& target_variable_smiles
    );

    /// \brief Apply an observed single-cut variable transform to a source SMILES.
    ///
    /// \param source_smiles Source molecule SMILES.
    /// \param variable_transform_smiles Transform string in
    ///     ``source_variable>>target_variable`` form.
    /// \returns Deduplicated canonical product SMILES records.
    /// \throws InvalidMoleculeError If the source SMILES is invalid.
    /// \throws InvalidQueryError If the transform is malformed or unsupported.
    static std::vector<TransformProduct> ApplyVariableTransform(
        const std::string& source_smiles,
        const std::string& variable_transform_smiles
    );

    /// \brief Apply an observed single-cut variable transform to an OpenEye molecule.
    ///
    /// \param source_mol Source molecule.
    /// \param variable_transform_smiles Transform string in
    ///     ``source_variable>>target_variable`` form.
    /// \returns Deduplicated canonical product SMILES records.
    /// \throws InvalidMoleculeError If the source molecule has no atoms.
    /// \throws InvalidQueryError If the transform is malformed or unsupported.
    static std::vector<TransformProduct> ApplyVariableTransform(
        const OEChem::OEMolBase& source_mol,
        const std::string& variable_transform_smiles
    );

    /// \brief Apply the transform represented by a matched pair.
    ///
    /// \param pair Matched-pair result whose source molecule and variable
    ///     transform define the application.
    /// \returns Deduplicated canonical product SMILES records.
    /// \throws InvalidMoleculeError If the pair source SMILES is invalid.
    /// \throws InvalidQueryError If the pair transform is malformed or unsupported.
    static std::vector<TransformProduct> ApplyPairTransform(const MatchedPair& pair);
};

}  // namespace OEMMPA

#endif  // OEMMPA_TRANSFORM_APPLICATION_H
