#ifndef OEMMPA_TRANSFORM_APPLICATION_H
#define OEMMPA_TRANSFORM_APPLICATION_H

#include <string>
#include <vector>

#include <oechem.h>

#include "oemmpa/MatchedPair.h"
#include "oemmpa/Transform.h"

namespace OEMMPA {

/// \brief Product generated by applying a transform.
class TransformProduct {
public:
    TransformProduct() = default;
    explicit TransformProduct(const std::string& smiles);

    /// \brief Canonical product SMILES.
    ///
    /// \returns Canonical product SMILES generated by OpenEye.
    const std::string& GetSmiles() const;

private:
    std::string smiles_;
};

/// \brief Options controlling collection-level product generation.
class GenerationOptions {
public:
    /// \brief Minimum transform evidence required before application.
    ///
    /// A value of zero disables evidence filtering.
    ///
    /// \returns Minimum evidence count.
    unsigned int GetMinEvidence() const;

    /// \brief Set the minimum transform evidence required before application.
    ///
    /// \param min_evidence Minimum evidence count. Use zero to disable evidence
    ///     filtering.
    void SetMinEvidence(unsigned int min_evidence);

    /// \brief Whether unsupported observed transforms are skipped.
    ///
    /// \returns ``true`` when unsupported transforms are skipped.
    bool GetSkipUnsupportedTransforms() const;

    /// \brief Set whether unsupported observed transforms are skipped.
    ///
    /// \param skip_unsupported_transforms When ``true``, malformed or
    ///     unsupported observed transforms are ignored during collection-level
    ///     generation. When ``false``, those errors propagate.
    void SetSkipUnsupportedTransforms(bool skip_unsupported_transforms);

private:
    unsigned int min_evidence_ = 1;
    bool skip_unsupported_transforms_ = true;
};

/// \brief Product row generated from a transform collection.
class GeneratedProduct {
public:
    GeneratedProduct() = default;
    GeneratedProduct(
        const std::string& smiles,
        const std::string& transform_smiles,
        unsigned int evidence_count
    );

    /// \brief Canonical product SMILES.
    ///
    /// \returns Canonical product SMILES generated by OpenEye.
    const std::string& GetSmiles() const;

    /// \brief Transform responsible for this product row.
    ///
    /// \returns Observed transform SMILES.
    const std::string& GetTransformSmiles() const;

    /// \brief Number of matched pairs evidencing the transform.
    ///
    /// \returns Transform evidence count.
    unsigned int GetEvidenceCount() const;

private:
    std::string smiles_;
    std::string transform_smiles_;
    unsigned int evidence_count_ = 0;
};

/// \brief Applies chemically explicit molecular transforms.
class TransformApplicator {
public:
    /// \brief Apply a unimolecular transform SMIRKS to a source SMILES.
    ///
    /// \param source_smiles Source molecule SMILES.
    /// \param transform_smirks Chemically explicit unimolecular SMIRKS.
    /// \returns Deduplicated canonical product SMILES records.
    /// \throws InvalidMoleculeError If the source SMILES is invalid.
    /// \throws InvalidQueryError If the transform SMIRKS cannot be parsed.
    static std::vector<TransformProduct> ApplySmirks(
        const std::string& source_smiles,
        const std::string& transform_smirks
    );

    /// \brief Apply a unimolecular transform SMIRKS to an OpenEye molecule.
    ///
    /// \param source_mol Source molecule.
    /// \param transform_smirks Chemically explicit unimolecular SMIRKS.
    /// \returns Deduplicated canonical product SMILES records.
    /// \throws InvalidMoleculeError If the source molecule has no atoms.
    /// \throws InvalidQueryError If the transform SMIRKS cannot be parsed.
    static std::vector<TransformProduct> ApplySmirks(
        const OEChem::OEMolBase& source_mol,
        const std::string& transform_smirks
    );

    /// \brief Convert an observed variable transform to SMIRKS.
    ///
    /// \param variable_transform_smiles Transform string in
    ///     ``source_variable>>target_variable`` form.
    /// \returns Reaction-ready SMIRKS for supported connected variables with
    ///     one to three attachment labels.
    /// \throws InvalidQueryError If the transform is malformed or unsupported.
    static std::string BuildVariableTransformSmirks(
        const std::string& variable_transform_smiles
    );

    /// \brief Convert observed variables to SMIRKS.
    ///
    /// \param source_variable_smiles Source variable SMILES.
    /// \param target_variable_smiles Target variable SMILES.
    /// \returns Reaction-ready SMIRKS for supported connected variables with
    ///     one to three attachment labels.
    /// \throws InvalidQueryError If either variable is malformed or unsupported.
    static std::string BuildVariableTransformSmirks(
        const std::string& source_variable_smiles,
        const std::string& target_variable_smiles
    );

    /// \brief Apply an observed variable transform to a source SMILES.
    ///
    /// \param source_smiles Source molecule SMILES.
    /// \param variable_transform_smiles Transform string in
    ///     ``source_variable>>target_variable`` form.
    /// \returns Deduplicated canonical product SMILES records.
    /// \throws InvalidMoleculeError If the source SMILES is invalid.
    /// \throws InvalidQueryError If the transform is malformed or unsupported.
    static std::vector<TransformProduct> ApplyVariableTransform(
        const std::string& source_smiles,
        const std::string& variable_transform_smiles
    );

    /// \brief Apply an observed variable transform to an OpenEye molecule.
    ///
    /// \param source_mol Source molecule.
    /// \param variable_transform_smiles Transform string in
    ///     ``source_variable>>target_variable`` form.
    /// \returns Deduplicated canonical product SMILES records.
    /// \throws InvalidMoleculeError If the source molecule has no atoms.
    /// \throws InvalidQueryError If the transform is malformed or unsupported.
    static std::vector<TransformProduct> ApplyVariableTransform(
        const OEChem::OEMolBase& source_mol,
        const std::string& variable_transform_smiles
    );

    /// \brief Apply the transform represented by a matched pair.
    ///
    /// \param pair Matched-pair result whose source molecule and variable
    ///     transform define the application.
    /// \returns Deduplicated canonical product SMILES records.
    /// \throws InvalidMoleculeError If the pair source SMILES is invalid.
    /// \throws InvalidQueryError If the pair transform is malformed or unsupported.
    static std::vector<TransformProduct> ApplyPairTransform(const MatchedPair& pair);

    /// \brief Generate products from a transform collection and source SMILES.
    ///
    /// Applies each supported observed transform to ``source_smiles`` after
    /// evidence filtering. Product rows retain the transform and evidence count
    /// that generated them.
    ///
    /// \param source_smiles Source molecule SMILES.
    /// \param transforms Candidate transform collection.
    /// \param options Generation options.
    /// \returns Deduplicated product rows by product SMILES and transform.
    /// \throws InvalidMoleculeError If the source SMILES is invalid.
    /// \throws InvalidQueryError If an unsupported transform is encountered
    ///     and ``GenerationOptions::GetSkipUnsupportedTransforms()`` is
    ///     ``false``.
    static std::vector<GeneratedProduct> GenerateProducts(
        const std::string& source_smiles,
        const std::vector<Transform>& transforms,
        const GenerationOptions& options = GenerationOptions()
    );

    /// \brief Generate products from a transform collection and OpenEye molecule.
    ///
    /// \param source_mol Source molecule.
    /// \param transforms Candidate transform collection.
    /// \param options Generation options.
    /// \returns Deduplicated product rows by product SMILES and transform.
    /// \throws InvalidMoleculeError If the source molecule has no atoms.
    /// \throws InvalidQueryError If an unsupported transform is encountered
    ///     and ``GenerationOptions::GetSkipUnsupportedTransforms()`` is
    ///     ``false``.
    static std::vector<GeneratedProduct> GenerateProducts(
        const OEChem::OEMolBase& source_mol,
        const std::vector<Transform>& transforms,
        const GenerationOptions& options = GenerationOptions()
    );
};

}  // namespace OEMMPA

#endif  // OEMMPA_TRANSFORM_APPLICATION_H
