#ifndef OEMMPA_TRANSFORM_APPLICATION_H
#define OEMMPA_TRANSFORM_APPLICATION_H

#include <string>
#include <vector>

#include <oechem.h>

namespace OEMMPA {

/// \brief Product generated by applying a transform.
class TransformProduct {
public:
    TransformProduct() = default;
    explicit TransformProduct(const std::string& smiles);

    /// \brief Canonical product SMILES.
    ///
    /// \returns Canonical product SMILES generated by OpenEye.
    const std::string& GetSmiles() const;

private:
    std::string smiles_;
};

/// \brief Applies chemically explicit molecular transforms.
class TransformApplicator {
public:
    /// \brief Apply a unimolecular transform SMIRKS to a source SMILES.
    ///
    /// \param source_smiles Source molecule SMILES.
    /// \param transform_smirks Chemically explicit unimolecular SMIRKS.
    /// \returns Deduplicated canonical product SMILES records.
    /// \throws InvalidMoleculeError If the source SMILES is invalid.
    /// \throws InvalidQueryError If the transform SMIRKS cannot be parsed.
    static std::vector<TransformProduct> ApplySmirks(
        const std::string& source_smiles,
        const std::string& transform_smirks
    );

    /// \brief Apply a unimolecular transform SMIRKS to an OpenEye molecule.
    ///
    /// \param source_mol Source molecule.
    /// \param transform_smirks Chemically explicit unimolecular SMIRKS.
    /// \returns Deduplicated canonical product SMILES records.
    /// \throws InvalidMoleculeError If the source molecule has no atoms.
    /// \throws InvalidQueryError If the transform SMIRKS cannot be parsed.
    static std::vector<TransformProduct> ApplySmirks(
        const OEChem::OEMolBase& source_mol,
        const std::string& transform_smirks
    );
};

}  // namespace OEMMPA

#endif  // OEMMPA_TRANSFORM_APPLICATION_H
